// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkHUkG8ycJrvDZ_c1Hqiw4DEjEX-Q-T0',
    appId: '1:320689859510:web:5bb75c8ccea291b4a5ef17',
    messagingSenderId: '320689859510',
    projectId: 'tesloginregis-ef264',
    authDomain: 'tesloginregis-ef264.firebaseapp.com',
    storageBucket: 'tesloginregis-ef264.appspot.com',
    measurementId: 'G-FC5Y1D5Y2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvrPP-6sH6L7_Nap05k-ZLUyZL3KOUqI',
    appId: '1:320689859510:android:d2971c8c0ecd4295a5ef17',
    messagingSenderId: '320689859510',
    projectId: 'tesloginregis-ef264',
    storageBucket: 'tesloginregis-ef264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKx6T-uZIXc6RtH-PLRSH4Us82kkC02M',
    appId: '1:320689859510:ios:51b5ff6aff584044a5ef17',
    messagingSenderId: '320689859510',
    projectId: 'tesloginregis-ef264',
    storageBucket: 'tesloginregis-ef264.appspot.com',
    iosBundleId: 'com.example.loginAndRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKx6T-uZIXc6RtH-PLRSH4Us82kkC02M',
    appId: '1:320689859510:ios:51b5ff6aff584044a5ef17',
    messagingSenderId: '320689859510',
    projectId: 'tesloginregis-ef264',
    storageBucket: 'tesloginregis-ef264.appspot.com',
    iosBundleId: 'com.example.loginAndRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkHUkG8ycJrvDZ_c1Hqiw4DEjEX-Q-T0',
    appId: '1:320689859510:web:25261d1ae5552842a5ef17',
    messagingSenderId: '320689859510',
    projectId: 'tesloginregis-ef264',
    authDomain: 'tesloginregis-ef264.firebaseapp.com',
    storageBucket: 'tesloginregis-ef264.appspot.com',
    measurementId: 'G-B2QXFK1HC3',
  );
}
